In [ ]:
import numpy as np

a=np.array([10,20,30])
b=np.array([40,50,60])
print(a)
print(b)
print(a*b)

In [1]:
ls1=[10,20,30]
ls2=[40,50,60]
print(ls1+ls2)


[10, 20, 30, 40, 50, 60]


In [ ]:
#creation. indexing,slicing of nympy array

ss=np.array([10,20,30,40])

print(ss[0:3])#first three elements
print(ss[0:])# start from zero index to end
print(ss[3:])#after index three to end
print(ss[2:])# after index two to end
print(ss[:3])# for getting first three element

sss=np.array([[10,20,30,40],[60,70,90,80]])
print(sss[0:2,0:2])# for getting first two element from each sub array 
print(sss[0:2,0:3])# we will get three element for each array
print(sss[0,1:3])# index 0, starting value 1 & ending value three
print(sss[1,2:4])#index 1 means (second one), staring value 2 and ending value 4






s=np.array([[10,20,30,40],[60,70,90,80],[12,23,34,45]])
print(s)
print(type(s))
print(s[2,2])#2nd number index and 2nd number element
#attributies of array
print(np.shape(s))#rows & columns
print(np.size(s))#total elements
print(np.ndim(s))
print(np.size(s))



In [ ]:
#inspecting an array
arr=[[12,23,20],[23,21,40]]
a=np.array(arr)
print(a)
print(a.shape)# answer shows the number of columns and number of rows
print(len(a))#number of size of an array(number of nested values)
print(np.size(a))#number of array elements 
print(type(a))#f type of variable
print(a.dtype)# data type of array elements
print(a.astype(float))# converting data type


In [ ]:
#mathmetical operaton & function on arrays

arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1+arr2)
print(np.add(arr1,arr2))

In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

In [ ]:
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

In [ ]:

arr1=np.array([[10,20],[30,40]])
arr2=np.array([2])

print(np.power(arr1,arr2))

In [ ]:

arr1=np.array([[10,20],[30,40]])


print(np.sqrt(arr1))

In [ ]:
#combing and spiliting array

#concatenate
a=np.array([1,2,3,])
b=np.array([4,5,6,])
print(np.concatenate([a,b]))

In [ ]:
#concatenate
a=np.array([[1,2],[0,3,]])
b=np.array([[4,5,],[10,6,]])
#print(np.concatenate([a,b]), axis=1)
print(np.hstack([a,b])) #horizontal concatination
print(np.vstack([a,b])) # vertical concatination 

In [1]:
#spliting
a=np.array([10,20,30,40,50,60])
b=np.array_split(a,3)
print(b)
b=np.array_split(a,4)
print(b)
b=np.array_split(a,5)
print(b)


a=np.array([[10,20,30],[40,50,60]])
b=np.array_split(a,2)
print(b)

NameError: name 'np' is not defined

In [6]:
#adding and removing element from an array

import numpy as np
#a=np.array([20,40,60,80])
#print(np.append(a,90))

a=np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [23]:


print(a)
print(np.delete(a,1))# axis=1

[20 40 60 80]
[20 60 80]


In [35]:
#sorttin, filter, search

import numpy as np

ar=np.array([[2,1,5,3,6,7,12],[2,7,1,6,3,0,3]])
print(np.sort(ar))
 

[[ 1  2  3  5  6  7 12]
 [ 0  1  2  3  3  6  7]]


In [37]:
a=np.array([2,3,1,5,6,7])
#s=np.where(a == 3)
s=np.where(a % 2 == 0)
print(s)

(array([0, 4]),)


In [39]:
a=np.array([2,3,4,5,6,7])
s=np.searchsorted(a,5)
print(s)

3


In [42]:
a=np.array([2,3,4,5,6,7])
#fi=[True, False,True, False, False,True ]
fi=a<4
new=a[fi]
print(new)

[2 3]


In [45]:
#aggregating functions in numpy

a=np.array([20,40,60,80])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

200
80
20
4
50.0
[ 20  60 120 200]
[     20     800   48000 3840000]


In [50]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

price=np.array(a)
quantity=np.array(b)

print(price, "\n", quantity)
print()
c=np.cumprod([price, quantity])
print(c[1].sum())

[10 20 30 40] 
 [1 2 3 4]

200


In [55]:
#statiscal function

import statistics as stats

food_price=[200,400,102,300,203,700,456]
a=np.array(food_price)
print(np.mean(a))
print(np.median(a))#centaral value aftr sorting
print(stats.mode(a))
print(np.std(a))#standers deviation
print(np.var(a))# square of std  for example 23**2


337.2857142857143
300.0
200
186.40103792301025
34745.34693877551


In [2]:
#duto data r majhe jodi compare kore dekha hoy je kontar karone kontar man increase hochhe na decrease hochhe tobe shekhane corrcoef use kora hoy
import numpy as np

price=[200,300,400,230,4010]
sales=[10,30,40,20,43]

print(np.corrcoef([price,sales]))


#-1 means inversly propotional relationship
#1 means propotional relationship
#0 means no relationship

[[1.         0.62011202]
 [0.62011202 1.        ]]
